In [1]:
from scipy.spatial import distance
import pickle
import torch
from torch import linalg
import numpy as np
from scipy.linalg import cho_solve

/Users/patricktourniaire/opt/miniconda3/envs/nmmm/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
def load_object(repo: str, file: str):
    # Path constant to save the object
    PATH = f'{repo}/{file}.pkl'

    with open(PATH, 'rb') as f:
        return pickle.load(f)

In [3]:
features = load_object('../../data/train', 'donut')
features = torch.from_numpy(features)

In [4]:
print(features)
print(features.shape)
reshaped_feats = features.t() #torch.reshape(features, (2, 1000))
print(reshaped_feats)
print(features.t())

tensor([[ 4.8302,  1.7729],
        [-3.0147,  3.6299],
        [-2.7704, -4.4909],
        ...,
        [-3.2588,  3.8029],
        [-4.8496,  2.3319],
        [ 3.7889,  3.3190]], dtype=torch.float64)
torch.Size([1000, 2])
tensor([[ 4.8302, -3.0147, -2.7704,  ..., -3.2588, -4.8496,  3.7889],
        [ 1.7729,  3.6299, -4.4909,  ...,  3.8029,  2.3319,  3.3190]],
       dtype=torch.float64)
tensor([[ 4.8302, -3.0147, -2.7704,  ..., -3.2588, -4.8496,  3.7889],
        [ 1.7729,  3.6299, -4.4909,  ...,  3.8029,  2.3319,  3.3190]],
       dtype=torch.float64)


In [133]:
means = torch.zeros(2, dtype=torch.float64).normal_()
sigma = torch.zeros(2, 2, dtype=torch.float64).normal_()
L = torch.linalg.cholesky(sigma @ sigma.t() + torch.eye(2))
print(L)

tensor([[1.8112, 0.0000],
        [0.5413, 1.1104]], dtype=torch.float64)


In [147]:
torch.diag(torch.diag(L)) @ torch.diag(torch.diag(L)).t()

tensor([[3.2803, 0.0000],
        [0.0000, 1.2329]], dtype=torch.float64)

In [143]:
torch.diag(sigma)

tensor([-1.5071, -0.2819], dtype=torch.float64)

In [72]:
a = torch.linalg.cholesky(torch.tril(sigma) @ torch.tril(sigma).t())

print(a)

tensor([[0.7870, 0.0000],
        [0.0178, 1.1794]], dtype=torch.float64)


In [117]:
A = 15 * torch.ones(2, 1, 1) * torch.eye(2, 2).view(1, 2, 2)
A = (A).type(torch.FloatTensor)

In [132]:
torch.tril(torch.diag(sigma[0][:2]))

tensor([[ 0.7870,  0.0000],
        [ 0.0000, -1.2324]], dtype=torch.float64)

In [125]:
torch.diag(A[0]).reshape(2)

tensor([15., 15.])

In [85]:
(torch.matmul(A, A.transpose(1, 2))).view(
            2, 2 * 2
        ) / 2

tensor([[112.5000,   0.0000,   0.0000, 112.5000],
        [112.5000,   0.0000,   0.0000, 112.5000]])

In [109]:
A = 15 * torch.ones(3, 1, 1) * torch.eye(2, 2).view(1, 2, 2)
A = (A).type(torch.FloatTensor).contiguous()
print(torch.tril(A))
print(A)

tensor([[[15.,  0.],
         [ 0., 15.]],

        [[15.,  0.],
         [ 0., 15.]],

        [[15.,  0.],
         [ 0., 15.]]])
tensor([[[15.,  0.],
         [ 0., 15.]],

        [[15.,  0.],
         [ 0., 15.]],

        [[15.,  0.],
         [ 0., 15.]]])


In [90]:
L

tensor([[15.,  0.],
        [ 0., 15.]])

In [91]:
S

tensor([[225.,   0.],
        [  0., 225.]])